Add scripts for signing merkle trees
api3dao/dapi-management pull request #2
Opened 2023-10-12 17:27 UTC by alikonuk1

closes [api3dao/tasks#194](https://github.com/api3dao/tasks/issues/194)

2023-10-13 14:51 UTC, acenolaza commented on scripts/merkle/dapiManagementMT.js
> +const tree = constructMerkleTree(values, ['string', 'bytes32', 'address']);
While working on `DapiDataRegistry` I started thinking that is nice to have `dapiName: 'API3/USD'` string in the dapiManagementMT.json metadata file but shouldn't we construct the merkle tree with the `bytes32` string instead since even the `DapiServer.sol` is expecting to received the formatted `bytes32` string when calling `SetDapiName()`?
```suggestion
const tree = constructMerkleTree(values, ['bytes32', 'bytes32', 'address']);
```

2023-10-13 16:27 UTC, bbenligiray commented on scripts/merkle/dapiManagementMT.js
> +const tree = constructMerkleTree(values, ['string', 'bytes32', 'address']);
Yes, the contract wouldn't be able to convert `string` to `bytes32` aynway

2023-10-13 16:50 UTC, acenolaza commented on scripts/merkle/dapiManagementMT.js
> +const tree = constructMerkleTree(values, ['string', 'bytes32', 'address']);
I guess it is now possible to do something like the following to convert it but it would consume more gas as well:
`api3ServerV1.setDapiName(bytes32(abi.encodePacked(dapiName)), dataFeedId);`

2023-10-16 10:09 UTC, bbenligiray requested changes
Thanks, this is generally what is asked in the issue

A few requests:
- The signing scripts have a lot of code duplication between them. Can you implement them as a single script that works according to the hash type?
- I can't tell what the fields are in the JSON files. Can you document in the README how we should be using them?
- Also, can you add the file that keeps the list of root signers? For now you can populate it with the default hardhat signers.

2023-10-16 10:10 UTC, bbenligiray commented on package.json
> +    "@openzeppelin/contracts": "4.9.3",
Shouldn't need these

2023-10-16 10:12 UTC, bbenligiray commented on scripts/merkle/treeValues/apiIntegrationMT.json
> +{
Move these JSON files (and the list of root signers) in `data/` at the repo root (a bit like https://github.com/api3dao/manager-multisig/tree/main/chain/fallback). These files will keep the actual values when we go to production, may as well set it up now.

2023-10-16 15:38 UTC, bbenligiray commented on scripts/merkle/dapiManagementMT.js
> +const tree = constructMerkleTree(values, ['string', 'bytes32', 'address']);
`bytes32(abi.encodePacked(stringVariable))` truncates the string down to 32 characters so that's not really an option imo

2023-10-19 19:21 UTC, acenolaza commented on scripts/signMerkleTree.js
> +  chainId: 1,
Since this script is not run using hardhat then I guess the `chainId` should come as command line arg, right?

2023-10-19 19:21 UTC, acenolaza commented on scripts/signMerkleTree.js
> +  verifyingContract: '0x0000000000000000000000000000000000000000',
This can be read from `references.json` (to be added I guess)

2023-10-19 19:21 UTC, acenolaza commented on README.md
> +yarn sign [MerkleTreeName]
Since `MerkleTreeName` becomes the `hashType` should we document where to get them from? [I've added 2 of the 4](https://github.com/api3dao/dapi-management/blob/169-DapiDataRegistry/contracts/DapiDataRegistry.sol#L25-L28) to DapiDataRegistry (price I'm not sure and fallback should be added to DapiFallbackV2 I guess)

2023-10-19 19:21 UTC, acenolaza commented on scripts/signMerkleTree.js
> +};
I've just now realized that the [descriptions](https://github.com/api3dao/dapi-management/blob/169-DapiDataRegistry/contracts/DapiDataRegistry.sol#L25-L28) I used in DapiDataRegistry do not match the ones used as keys in here 😁

2023-10-19 19:21 UTC, acenolaza commented on scripts/signMerkleTree.js
> +}
These functions are probably going to be handy for frontend signing as well, right? I wonder if we should  export them from their own module. signEIP712Message might need to receive a PK as arg instead of relying on a global `wallet` object

2023-10-23 15:07 UTC, alikonuk1 commented on README.md
> +      "signatures": {}
Yeah so conclusion was keeping it this way if I remember correctly 😄

2023-10-23 15:09 UTC, alikonuk1 commented on README.md
> +  ],
Oh good catch. This makes me want to divide json files by their hashType's, would be seen tidier maybe?

2023-10-23 16:21 UTC, alikonuk1 commented on scripts/signMerkleTree.js
> +  verifyingContract: '0x0000000000000000000000000000000000000000',
Yes it will be added when we have `references.json`. I think we will have to wait for deploy scripts for it?

2023-10-23 21:48 UTC, acenolaza commented on README.md
> +  ],
Or you can just have a `rootSigners` array within each merkle tree type (right above timestamp for each type)

2023-10-23 21:50 UTC, acenolaza commented on scripts/signMerkleTree.js
> +  verifyingContract: '0x0000000000000000000000000000000000000000',
Yes, I guess those will be added [here](https://github.com/api3dao/tasks/issues/196)

2023-10-25 11:40 UTC, bbenligiray requested changes
The Merkle tree names:
- ~Price Merkle tree~ -> dAPI pricing Merkle tree
- dAPI management Merkle tree
- dAPI fallback Merkle tree
- ~API integration Merkle tree~ -> Signed API URL Merkle tree

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +  ],
Each MT type will have its own directory with a `metadata.json` file each. This will go in there. Alternatively, just have a `root-signers.json` file, as that is the only metadata field.

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +      "signatures": {}
It's a good idea to bundle the signatures with the tree values considering that there will be two sets of tree values (`current` and `previous`)

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +    "priceMT": {
I'm seeing `priceMT`, `Price Merkle Tree`, `Price merkle tree root` in the PR. Pick a name for each and use them consistently.

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +      "merkleRoot": "",
No need for the root

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +  - **Signed API URL (bytes32)**: The signed URL of the API, hashed. Verified by referring to the DNS records of the base URL.
This is not hashed, it's the full URL as a `string`

2023-10-25 11:40 UTC, bbenligiray commented on README.md
> +  - **Nodary Sponsor Wallet Address (address)**: Wallet address of the Nodary sponsor wallet.
There is nothing Nodary-specific about the schema of the Merkle tree. Any other data feed ID would work here.

2023-10-25 11:40 UTC, bbenligiray commented on data/metadata.json
> +    "Price merkle tree root": {
If the parent key is `merkleTrees`, you can't name this `Price merkle tree root` (a tree is not a root)

2023-10-25 11:45 UTC, bbenligiray commented
```
data/
├─ dapi-pricing-merkle-tree-root/
│  ├─ hash-signers.json
│  ├─ current-hash.json
├─ dapi-management-merkle-tree-root/
│  ├─ hash-signers.json
│  ├─ current-hash.json
│  ├─ previous-hash.json
├─ dapi-fallback-merkle-tree-root/
│  ├─ hash-signers.json
│  ├─ current-hash.json
├─ signed-api-url-merkle-tree/
│  ├─ hash-signers.json
│  ├─ package.json
```

2023-10-25 11:47 UTC, bbenligiray commented on README.md
> +      "merkleRoot": "",
Actually we can do something like this
```
{
  "timestamp": 1676940000,
  "hash": "0x1234...",
  "signatures": {
  },
  "merkleTreeValues": {
  }
}
```
where `merkleTreeValues` is optional. This can then support arbitrary hash types (not only Merkle tree roots) in the future.

2023-10-25 11:51 UTC, bbenligiray commented on scripts/signMerkleTree.js
> +  chainId: chainId,
This implies that we'll need to sign all Merkle tree roots once per each chain, which wasn't the plan. We can hardcode a chain ID here, but EIP712.sol gets its chain ID from the chain, so it wouldn't work.

I guess leave this as is, but the contract and these scripts will have to be updated later to use ERC191 instead.

2023-10-25 11:54 UTC, bbenligiray commented
Apply the changes above and ask for another review (DM on Slack) and let's merge it then because this remained open for far too long. If I want any other changes I can open a PR of my own.

2023-10-25 14:27 UTC, bbenligiray approved these changes
You should commit the fixes individually, I won't bother checking this

2023-10-25 14:37 UTC, merged