Api3Market contract #170
api3dao/dapi-management pull request #26
Opened 2023-10-27 21:42 UTC by acenolaza

Create a ginormous `buyDapi()` function because I wanted to lay out all the initial requirements. We can split this function and ask the caller to use `multicall` but we might need to add checks to functions that require one to be call before the other.

As usual, there a bunch of TODOs with questions and early feedback is always welcome 🙏🏻

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +            //       Should we add that check to avoid re-setting the same value to state if values are equal?
Multi-call DapiDataRegistry to fetch all signed API URLs, only register the ones that don't match

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: dAPI purchases will always use beaconSets or will there be purchases that will point to a single beacon?
There will be single Beacon dAPIs

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        //       downgraded to 1% after 3 months
Yes, ideally

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: should we derive the data feed ID based on the airnodes and templateIds to see if it matches the dataFeedId parameter?
Why would there be a dataFeedId parameter to begin with?

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: Should we only sent the delta between price and sponsor wallet balance? If so, what to do with the rest?
No, forward the entire `msg.value`

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: Will this contract require a withdraw() function?
Don't see why it would with the above

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        require(msg.value >= args.price, "Insufficient payment");
You're not considering the sponsor wallet balance?

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        Address.sendValue(args.sponsorWallet, msg.value);
Do this last, this is the least-trusted external call

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: check if proxy has been deployed (see: https://github.com/api3dao/airnode-protocol-v1/blob/v2.10.0/contracts/api3-server-v1/proxies/ProxyFactory.sol#L140)
Yes

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // Update the dAPI with signed API data (if it hasn't been updated recently, what's recently?)
Recently = last `heartbeatInterval`

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: why signed data? shouldn't we instead just call updateBeaconSetWithBeacons()?
If the Beacons haven't been updated recently, `updateBeaconSetWithBeacons()` doesn't do anything

2023-10-30 09:59 UTC, bbenligiray commented on contracts/Api3Market.sol
> +        // TODO: emit event (include proxyAddress?)
Yes, and updated sponsor wallet balance

2023-10-30 15:08 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: should we derive the data feed ID based on the airnodes and templateIds to see if it matches the dataFeedId parameter?
Right, good catch

2023-10-30 18:15 UTC, acenolaza commented on contracts/Api3Market.sol
> +            //       Should we add that check to avoid re-setting the same value to state if values are equal?
Ok but just to in case the comment wasn't clear my suggestion was more about adding an `if` statement to the `DapiDataRegistry.registerAirnodeSignedApiUrl` function like so:

```
        if (
            keccak256(abi.encodePacked((airnodeToSignedApiUrl[airnode]))) !=
            keccak256(abi.encodePacked((url)))
        ) {
            airnodeToSignedApiUrl[airnode] = url;

            emit RegisteredSignedApiUrl(airnode, url);
        }
```

2023-10-30 18:34 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: Will this contract require a withdraw() function?
My worry was that we might end up with locked funds in the contract but I guess that wouldn't happen if we don't have a `receive() payable` or `fallback() payable` functions (there are some other weird ways to receive funds in this contract like being a recipient of selfdestruct but I don't think is worth considering). Another way to mitigate this could be to forward `address(this).balance` instead of `msg.value` 🤔

2023-10-30 19:22 UTC, acenolaza commented on contracts/Api3Market.sol
> +        require(msg.value >= args.price, "Insufficient payment");
You mean this?

```
require(
            msg.value >= (args.price - args.sponsorWallet.balance),
            "Insufficient payment"
        );
```

or are you referring to deducting balance from previous order when upgrading/downgrading while paid subscription is currently ongoing?

2023-10-30 19:23 UTC, acenolaza commented on contracts/Api3Market.sol
> +        //       downgraded to 1% after 3 months
I just now realized that the "3 months" subscription period from the example is not being stored on-chain 😟 and it feels like this should go into `DapiDataRegistry` along with deviation and heartbeat 🤔

2023-10-30 19:27 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: why signed data? shouldn't we instead just call updateBeaconSetWithBeacons()?
I guess this means that buyDapi() function needs to also receive signed data for each beacon in order to be able to call [updateBeaconWithSignedData()](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/api3-server-v1/BeaconUpdatesWithSignedData.sol#L26)

2023-10-30 19:36 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: emit event (include proxyAddress?)
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/ed0f9a544d180d216576740e4a111162790f5bf2

2023-10-30 23:41 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // Update the dAPI with signed API data (if it hasn't been updated recently, what's recently?)
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/62d64f97ea86a5d50641e101c304d67b65a8146c

2023-11-01 21:37 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: dAPI purchases will always use beaconSets or will there be purchases that will point to a single beacon?
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/75641b9c080f9b06147aba2473aa0f416310d3c0

2023-11-01 21:37 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: why signed data? shouldn't we instead just call updateBeaconSetWithBeacons()?
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/75641b9c080f9b06147aba2473aa0f416310d3c0

2023-11-01 21:49 UTC, acenolaza commented on contracts/Api3Market.sol
> +        //       downgraded to 1% after 3 months
https://api3workspace.slack.com/archives/C027Y2FAV0S/p1698740982751789?thread_ts=1698659099.119239&cid=C027Y2FAV0S

2023-11-06 20:19 UTC, alikonuk1 requested changes

2023-11-06 20:19 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        }
This would underflow if `purchases.length` is zero, and also when the loop reaches to zero.
```suggestion
        if (purchases.length == 0) {
            return purchases.length;
        }
        for (uint256 ind = purchases.length; ind > 0; ind--) {
            Purchase storage purchase = purchases[ind - 1];
            if (
                block.timestamp >= purchase.start &&
                block.timestamp < purchase.end
            ) {
                return ind - 1;
            }
        }
        return purchases.length;
```

2023-11-06 20:22 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +                    dapi.price,
We can use the `priceToPay` here instead of `dapi.price`

2023-11-07 06:13 UTC, alikonuk1 requested changes

2023-11-07 11:14 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        bytes32 dapiNameHash = keccak256(abi.encodePacked(args.dapi.name));
Also it will not work because mapping should be done with `args.dapi.name` ,
Here is how its stored in [DapiFallbakV2.sol](https://github.com/api3dao/dapi-management/blob/214fe632429f982661068dc117bdb66b7659f4b1/contracts/DapiFallbackV2.sol#L205C1-L208C11)

2023-11-07 11:16 UTC, acenolaza commented on contracts/Api3Market.sol
> +        bytes32 dapiNameHash = keccak256(abi.encodePacked(args.dapi.name));
That's an issue in `DapiFallbackV2`. Mapping key should be the hash of the `bytes32` encoded string

2023-11-07 19:49 UTC, acenolaza commented on contracts/Api3Market.sol
> +        bytes32 dapiNameHash = keccak256(abi.encodePacked(args.dapi.name));
Fixed in commit https://github.com/api3dao/dapi-management/pull/26/commits/c17dae6f65e5f9d783f16d248ccfebdc19e0074e

2023-11-07 19:49 UTC, acenolaza commented on contracts/Api3Market.sol
> +        }
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/eaa6f41e68c488c4760e84c17271f4296f89701d

2023-11-07 19:52 UTC, acenolaza commented on contracts/Api3Market.sol
> +                    dapi.price,
Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/c3bec2ebe07e96f5dc94a710ad350806c4a40028

2023-11-07 21:07 UTC, acenolaza commented on contracts/Api3Market.sol
> +    // This function must use the 3 Merkle trees to store the data needed for running a managed dAPI
I didn't do it explicitly in Api3Market because the other 2 are being validated by DapiDataRegistry [here](https://github.com/api3dao/dapi-management/blob/170-Api3Market/contracts/DapiDataRegistry.sol#L119-L124) and [here](https://github.com/api3dao/dapi-management/blob/170-Api3Market/contracts/DapiDataRegistry.sol#L219-L224).

2023-11-08 15:39 UTC, alikonuk1 requested changes

2023-11-08 17:08 UTC, acenolaza commented on contracts/Api3Market.sol
> +            for (uint256 ind = purchases.length - 1; ind >= 0; ind--) {
While that makes sense, I cannot get it to underflow. Maybe because of the version of solidity we are using which prevents from underflowing. This could be fixed by just using `int256` instead of `uint256` for the `ind` variable or WDYT we should do?

Here's an example that I've used on remix:

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.20;

contract Test {
    mapping(bytes32 => Purchase[]) public dapiToPurchases;

    struct Purchase {
        uint256 deviationThreshold;
        uint256 heartbeatInterval;
        uint256 price;
        uint256 duration;
        uint256 start;
        uint256 end;
    }

    constructor() {
        dapiToPurchases[0x9952ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db7].push(Purchase(1 ether, 1 days, 10 ether, 30 days, block.timestamp, block.timestamp + 30 days));
        dapiToPurchases[0x9952ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db7].push(Purchase(2 ether, 1 days, 5 ether, 30 days, block.timestamp + 30 days, block.timestamp + 60 days));
    }

    function _findCurrentDapiPurchaseIndex(
        bytes32 dapiNameHash
    ) external view returns (bool found, uint256 index) {
        Purchase[] storage purchases = dapiToPurchases[dapiNameHash];
        if (purchases.length > 0) {
            for (uint256 ind = purchases.length - 1; ind >= 0; ind--) {
                Purchase storage purchase = purchases[ind];
                if (
                    block.timestamp >= purchase.start &&
                    block.timestamp < purchase.end
                ) {
                    found = true;
                    index = ind;
                    break;
                }
            }
        }
    }
}
```

2023-11-08 18:53 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +            for (uint256 ind = purchases.length - 1; ind >= 0; ind--) {
If you give different bytes32 values like this 
```    
constructor() {
        dapiToPurchases[0x8882ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db8].push(Purchase(1 ether, 1 days, 10 ether, 30 days, block.timestamp, block.timestamp + 30 days));
        dapiToPurchases[0x9952ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db7].push(Purchase(2 ether, 1 days, 5 ether, 30 days, block.timestamp + 30 days, block.timestamp + 60 days));
    }
```
it will not revert on the index 0 (if you call it with `0x8882ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db8`). But if you start on index 1, it will start to revert (if you call it with `0x9952ba9fa4a96966154d47c3df79b8296db7225bc6685e414170b2c7cd4d1db7`).

2023-11-08 19:48 UTC, acenolaza commented on contracts/Api3Market.sol
> +            for (uint256 ind = purchases.length - 1; ind >= 0; ind--) {
Right, I'll just revert to previous for loop then. Fixed in https://github.com/api3dao/dapi-management/pull/26/commits/1b825657589ad65535e40a2bf0be2e2eb2892f2c

2023-11-09 19:28 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        // TODO: in the case of downgrade/upgrade we must fund sponsorWallet with
Yes I think `_processPayment()` should return an updated amount and we should use that amount to send to the sponsor wallet. And also deduct it from the `msg.value` and return the amount to the caller.

2023-11-14 10:34 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        bytes32 dapiNameHash = keccak256(abi.encodePacked(args.dapi.name));
It seems like the fix got reverted at some point.

2023-11-14 11:11 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +                        dapi.price,
Why don't we use `updatedPrice` here instead of `dapi.price`

2023-11-14 11:59 UTC, acenolaza commented on contracts/Api3Market.sol
> +        bytes32 dapiNameHash = keccak256(abi.encodePacked(args.dapi.name));
I realized that dapi-management frontend would require to get the list of fallbacked dAPI names and not the hashes, that's why I ended up reverting the change on DapiFallbackV2 https://github.com/api3dao/dapi-management/pull/26/commits/f438ee3188295a7f1143c4170587f68cdab5137b

2023-11-14 12:45 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // TODO: in the case of downgrade/upgrade we must fund sponsorWallet with
https://github.com/api3dao/dapi-management/pull/26/commits/efb2a75c1e1d6eada336daa6a8c93db277735fb3

2023-11-14 12:50 UTC, acenolaza commented on contracts/Api3Market.sol
> +                        dapi.price,
Because I think we should store the actual cost of the dAPI instead of what the user payed (price minus remainder from previous subscription). This is because we might need to calculate the reminder again in the future in case we upgrade the upgrade

2023-11-14 21:59 UTC, acenolaza commented on contracts/Api3Market.sol
> +    function _isFallbacked(
Should we move this into a modifier named something like `onlyNotFallbacked` on `DapiFallbackV2` instead of having this function here?

2023-11-15 09:16 UTC, alikonuk1 requested changes

2023-11-15 09:16 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        // If purchase if future downgrade, then a worker needs to call the
How will the worker listen the pending purchases? Will it call `readCurrentAndPendingPurchases()` function periodically or should we emit some event?

2023-11-15 10:48 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +    function _isFallbacked(
But wouldnt we need to check it from the Api3Market again?

2023-11-15 13:51 UTC, acenolaza commented on contracts/Api3Market.sol
> +                    current.purchasedAt < block.timestamp - 1 days,
Good catch 👏🏻

2023-11-15 13:52 UTC, acenolaza commented on contracts/Api3Market.sol
> +    function _isFallbacked(
Right, I was still thinking about the merge of the 2 contracts but if we leave them separate then at most we can just move the function to DapiFallbackV2 and call it from Api3Market

2023-11-15 13:55 UTC, acenolaza commented on contracts/Api3Market.sol
> +        // If purchase if future downgrade, then a worker needs to call the
I guess both are valid options, it could listen (or fetch) to `BoughtDapi` events to keep track of downgrades by calling `readCurrentAndPendingPurchases()`. Are you thinking that it would be necessary to emit a specific event for downgrades only?

2023-11-15 14:04 UTC, alikonuk1 commented on contracts/Api3Market.sol
> +        // If purchase if future downgrade, then a worker needs to call the
I don't have strong opinions about it, what you described sounds good.

2023-11-15 14:35 UTC, alikonuk1 approved these changes

2023-11-15 21:01 UTC, merged