Endpoint for signing a merkle root
api3dao/dapi-management pull request #27
Opened 2023-10-30 10:21 UTC by pieterdub

Closes #16

Add nextjs endpoint to sign a merkle root.

Using `multi-manager sig` as reference sign the merkle tree using the static values that is been provided.

endpoint: `localhost:3001/api/sign-merkle-root`
body: 
```
{
        "signature": "0xfe2cd37f6922ecad2e6277165caf65b0a1ed8b854e21ceac45c8f34ed60e3a1150ed6957d7f3f00d40b9f63ad3016051d18513dfeb95b81f8ff362a7017440a11c",
        "address": "0x80efDd3bB15F2108C407049C5575490858800D47",
        "tree": "DAPI_FALLBACK"
}
```

2023-10-31 12:32 UTC, mcoetzee requested changes

2023-10-31 12:32 UTC, mcoetzee commented on frontend/pages/api/sign-merkle-root/index.ts
> +export interface SignMerkleRootRequest {
Let's use Zod here to validate the request body:
```ts
const requestBodySchema = z.object({ ... });
```
And then we can safeParse:
```ts
const parseResult = requestBodySchema.safeParse(req.body);
if (!parseResult.success) {
  return res.status(400).send(...
}
```

2023-10-31 12:32 UTC, mcoetzee commented on frontend/pages/api/sign-merkle-root/index.ts
> +export default function handler(req: NextApiRequest, res: NextApiResponse) {
I think we should ensure we are receiving a POST:
```ts
  if (req.method !== 'POST') {
    return res.status(405).send('Method not allowed');
  }
```

2023-11-01 07:46 UTC, pieterdub commented on frontend/pages/api/sign-merkle-root/index.ts
> +  currentHash.signatures[hashSigners.hashSigners.indexOf(address)] = signature;
This is being validated on the next step. If this is removed it will validate the previous signature for this address

2023-11-01 07:57 UTC, mcoetzee commented on frontend/pages/api/sign-merkle-root/index.ts
> +  currentHash.signatures[hashSigners.hashSigners.indexOf(address)] = signature;
Ah I'm with you now 👍

2023-11-01 09:09 UTC, mcoetzee requested changes
Looking good 👍

2023-11-01 09:09 UTC, mcoetzee commented on frontend/pages/api/sign-merkle-root.ts
> +    return res.status(400).send(`Invalid body:\n, ${JSON.stringify(parseResult.error.format())}`);
Minor: Hmm would probably make more sense (in the context of a API response) to send back JSON here rather than a formatted string:
```ts
return res.status(400).json(parseResult.error);
```

2023-11-01 09:09 UTC, mcoetzee commented on frontend/pages/api/sign-merkle-root.ts
> +type JSONValue = string | number | boolean | JSONObject | string[] | string[][];
I assume all this is copy-pasta'd from somewhere, I'm just struggling to see the need for it if all we need is:
```ts
writeFileSync(currentHashPath, JSON.stringify(validatedCurrentHash));
```

2023-11-01 12:06 UTC, mcoetzee approved these changes
Using `exec('yarn prettier');` simplified things nicely 🥂

2023-11-01 12:10 UTC, merged