WIP: Adds DapiDataRegistry.sol contract
api3dao/dapi-management pull request #3
Opened 2023-10-13 15:24 UTC by acenolaza

This contract is still a WIP but I have reached the point where I think I have covered most of the requirements for this contract and I've made quite a few assumptions that need to be checked. I've also have a couple of questions and I think is better to just add a TODO in the code instead of asking privately over slack. The main goal of this PR is getting feedback as early as possible while I keep adding tests 🙏🏻

2023-10-16 08:44 UTC, bbenligiray reviewed
Missing the registry update (because someone extended their subscription or upgraded the deviation threshold) but you probably know that

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 public immutable registerDataRole;
The convention is for the role description variable name, role description and the role variable name to all be the same. "Role" doesn't go in the description

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 public immutable registerDataRole;
Also proposing registrar as a short and descriptive alternative

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    modifier onlyRegisterDataRole() {
```suggestion
    modifier onlyRegistrar() {
```

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    modifier onlyRegisterDataRole() {
What I mean is when a modifier requires the sender to be a specific account, the convention is to call the modifier something like `onlyOwner`. `-Role` shouldn't go in here.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    modifier onlyRegisterDataRole() {
As another note, I avoid using this `onlyX` naming convention for role checking purposes because it's inaccurate, the manager can also call these even if it doesn't have the role. I used to do
```
    modifier onlyRegistrarOrManager() {
```
instead but I couldn't find an example of that

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    // TODO: use uint128 to pack both in a single 32 bytes slot?
Maybe

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        // int224 deviationReference; Currently not used by Airseeker v1
Not having this when we need it will be a big problem

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public dataFeedIdToDataFeedData;
```suggestion
    mapping(bytes32 => bytes) public dataFeedIdToData;
```

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public dataFeedIdToDataFeedData;
In this `to` convention, I omit the duplicated subject

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes32 hashType,
This function should know what hash type it uses, it shouldn't ask the user

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes32 oisTitle;
Actually let's leave out `oisTitle` from here. If needed it can be a separate MT.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    // TODO1: Should anyone really be able to call this?
Yes

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    //        It would have a single element when beacon and multiple when beaconSet
A single Beacon Beacon set and a single Beacon are different data feeds with different IDs (even though there is no good reason to use a single Beacon Beacon set). I didn't like the ambiguity.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            Beacon memory beacon = abi.decode(dataFeedData, (Beacon));
`Beacon` and `beacon` feel to vague as variable names to me. It can be the IDs or the values. Also not a fan of encoding-decoding structs, too fancy.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            bytes[] memory beacons = abi.decode(dataFeedData, (bytes[]));
Why not decode into `(address[], bytes32[])`?

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        dataFeedIdToDataFeedData[dataFeedId] = dataFeedData;
Here's an interesting attack, I get the data feed data of a dAPI, add a huge bytes string at the end and re-register it, and the Airseeker stops being able to fetch it from the chain as a result. It feels like we should validate that data feed data should be exact/have no trailing data.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        uint256 deviationThreshold, // TODO: how to represent this? basis points? 0.25% == 25
Refer to https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/api3-server-v1/extensions/BeaconSetUpdatesWithPsp.sol#L111 for the time being

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes32 hashType,
Shouldn't ask the hash type

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function removeDapi(bytes32 dapiName) external {
This needs to be behind the role check

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        // TODO: should this function also return the Signed API URLs for each Airnode in the UpdateParameters?
Maybe. You need to be up to date with the airseeker-v2 discussions to be able to do this function correctly.

2023-10-16 08:44 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            bytes32[] memory dapiNameHashes,
It feels like we need dAPI names, not their hashes

2023-10-17 11:04 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        bytes32 hashType,
I agree and I almost didn't add this parameter in the first place but I wasn't sure which values to use for the hash type. I guess I should just add the hash types as constants in here.

2023-10-17 11:31 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            Beacon memory beacon = abi.decode(dataFeedData, (Beacon));
I must admit I saw this comment coming 🤭 and I might have over-used the `struct` data structure (too many years of OOP might be the cause)

2023-10-17 18:22 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function removeDapi(bytes32 dapiName) external {
This feels like it should require it's own role but at the same time I think the caller of this function is probably going to be the same as the caller of `registerDapi()` which is the `Registrar` role. WDYT?

A similar thing happens with `registerAirnodeSignedApiUrl()` function

2023-10-17 22:07 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            bytes[] memory beacons = abi.decode(dataFeedData, (bytes[]));
It felt more "correct" at the time since we are either sending a an encoded `bytes` for a `beacon` and encoded array of bytes for a `beaconSet`. The upside of this is that we don't have to worry about 2 arrays matching in length or in order of the elements but a downside is that it requires decoding in 2 steps (more gas). But I'll implement your suggestion since it probably makes more sense.

2023-10-18 15:33 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes32 oisTitle;
I've seen today that @metobom uses multiple OIS titles for an API provider because they have multiple base URLs, so this should definitely be left out because there is not a one-to-one mapping

2023-10-18 15:37 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function removeDapi(bytes32 dapiName) external {
Yeah, I think you can use the same role. I don't see your point about `registerAirnodeSignedApiUrl()` though. That's entirely MT-based/doesn't use roles?

2023-10-18 15:38 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function registerDapi(
I'm a bit irked by `registerDapi()`/`removeDapi()` naming. They are functionally opposite but semantically remove is not the opposite of register.

2023-10-18 15:38 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function registerDatafeed(
```suggestion
    function registerDataFeed(
```

2023-10-18 16:01 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        bytes32 oisTitle;
I'm really glad you noticed that 🥇

2023-10-18 16:09 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function removeDapi(bytes32 dapiName) external {
> I don't see your point about `registerAirnodeSignedApiUrl()` though. That's entirely MT-based/doesn't use roles?

You are absolutley right 🤦🏻 I got confused because Api3Market is supposed to call this function when making a purchase and Api3Market is going to need the role to be granted. I'll remove the access control for this function

2023-10-18 19:06 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerDapi(
Options:
`registerDapi()`/`unregisterDapi()`
`addDapi()`/`removeDapi()`
`activateDapi()`/`deactivateDapi()`
`enableDapi()`/`disableDapi()`
`saveDapi()`/`deleteDapi()`

2023-10-18 19:51 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
> if it's not included in the current Merkle tree

I'm assuming this check is done off-chain and the function should be behind access control

2023-10-18 20:43 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
Essentially, instead of removing it, we should be updating it whenever we have a new root.

2023-10-19 18:42 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +        for (uint256 ind = 0; ind < offset + limitAdjusted; ind++) {
Shouldn't we start the ind at offset?

2023-10-19 18:42 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +            dataFeedDatas[ind] = dataFeedIdToData[dataFeedId];
These would also go out of bound because of the comment above.

2023-10-19 19:28 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Is suggestion useful to make deployment cheaper? I used the same approach used for [roles and role descriptions](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/authorizers/RequesterAuthorizerWithAirnode.sol#L17-L21)

2023-10-19 19:29 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerDataFeed(
https://github.com/api3dao/dapi-management/pull/3#discussion_r1360308361 I was wondering the same 🤭

2023-10-19 19:39 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            dataFeedDatas[ind] = dataFeedIdToData[dataFeedId];
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/bb514a149c05cc089260ad8c5fffad4f483a3d04

2023-10-20 17:39 UTC, acenolaza commented
I must admit I'm not convinced about https://github.com/api3dao/dapi-management/pull/3/commits/867c251ebe0f902605400dd2e4d283173cd6033e. I'm returning an array of Signed API URLs where it will contain a single element if `dataFeedData` is a `beacon` and multiple when it is a `beaconSet`

2023-10-20 17:43 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            // TODO: check if signed API URL exists for Airnode?
This is something that came to mind after adding https://github.com/api3dao/dapi-management/pull/3/commits/867c251ebe0f902605400dd2e4d283173cd6033e

2023-10-20 17:43 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        // TODO: check if signed API URL is not being mappaed to an Airnode in dataFeedIdToData?
and this ...

2023-10-20 17:45 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        // TODO: should this function also return the Signed API URLs for each Airnode in the UpdateParameters?
Added Signed API URLs in https://github.com/api3dao/dapi-management/pull/3/commits/867c251ebe0f902605400dd2e4d283173cd6033e

2023-10-20 22:33 UTC, acenolaza commented
I've added the Data Feed Data to the readDapis() function 

> I must admit I'm not convinced about [867c251](https://github.com/api3dao/dapi-management/commit/867c251ebe0f902605400dd2e4d283173cd6033e). I'm returning an array of Signed API URLs where it will contain a single element if `dataFeedData` is a `beacon` and multiple when it is a `beaconSet`

BTW even dataFeedData was not supposed to be included in the readDapis() function according to the slides 🤔 https://docs.google.com/document/d/1x5QBOGII8IUGjtoNR6PVE_UeqEjRQj2u3Ysa1FQkHf0/edit?disco=AAAA8P8fNmA

2023-10-22 21:04 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +            deviationThresholdInPercentage, // TODO: can this be 0? should we check against any low/high boundary based on HUNDRED_PERCENT constant?
I think we may want to keep our option to make these parameters 0 incase of a removal maybe. So not restricting it to be always bigger than 0 feels like a safer option for me.

2023-10-22 23:19 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Saves 36973 gas on deployment, also feels tidier imo.

2023-10-23 06:15 UTC, Siegrift commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public dataFeedIdToData;
(As of now) This is supposed to hold the template IDs of the data feed?

2023-10-23 12:18 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
> Essentially, instead of removing it, we should be updating it whenever we have a new root.

I'm confused by this comment, you mind sharing an example or explain this a bit more 🙏🏻

2023-10-23 12:20 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public dataFeedIdToData;
Yes, this is an encoded `(airnode, templateId)` or `(airnode[], templateId[])`

2023-10-23 12:40 UTC, alikonuk1 commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
So what I meant was, if we are registering `url` values to this `airnodeToSignedApiUrl[airnode]` mapping by validating the values with the API integration Merkle tree, wouldn't it be an antipattern to unregister them without validating the values with the Merkle tree?

2023-10-23 13:01 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
Thanks, I get it now. I guess the issue is when you we stop supporting an API provider. How do you generate a proof for a value in the merkle tree which does not exist? I guess that is why I made the assumption this check was done off-chain and the remove function would be behind some access control role

2023-10-23 15:00 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/5887df34c350861570f24679f77d2031cfe11d67

2023-10-24 12:48 UTC, acenolaza commented
I don't know if [this](https://github.com/api3dao/dapi-management/pull/3/commits/37590f61e5ab4f98728ef05d3105ff38b5d95ef0) is the right place for this change but I didn't want to forget about it. If a separate PR is preferable then I'll move it.

2023-10-25 11:56 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function registerDapi(
`addDapi()`/`removeDapi()` feels fine

2023-10-25 12:00 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function registerAirnodeSignedApiUrl(
> How do you generate a proof for a value in the merkle tree which does not exist?

Huh, good point. I guess we have two options
- Let their signed API URLs remain in storage, it doesn't hurt us
- In the next Merkle tree, specify their signed API URL as `""` and register using that, which effectively deletes the previous one

Either way, we don't need a function to remove them. Feel free to resolve this thread.

2023-10-25 12:03 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Revert this, I'd much rather pay the extra gas then take the risk of the hash going outdated

2023-10-25 12:05 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    SelfMulticall,
This is redundant, `AccessControlRegistryAdminnedWithManager` inherits `SelfMulticall`

2023-10-25 12:07 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 public constant override DAPI_MANAGEMENT_HASH_TYPE =
Do this in a single line as in https://github.com/api3dao/omnimarket/blob/main/contracts/Omnimarket.sol#L81

2023-10-25 12:14 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    IApi3ServerV1 public immutable override api3ServerV1;
I declare these as `address` to avoid having to import `IHashRegistry.sol` and `IApi3ServerV1.sol` to `IDapiDataRegistry.sol`. I'm not sure if calling `IApi3ServerV1()` and `IDapiDataRegistry()` at runtime has an overhead though.

2023-10-25 12:14 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    // dAPI management merkle tree root
Capitalize Merkle

2023-10-25 12:15 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    // TODO: should this mapping be private now that we are returning these valuse via readDapis()
No

2023-10-25 12:15 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public override dataFeedIdToData;
Maybe call this `dataFeeds`

2023-10-25 12:16 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private activeDapis;
Maybe call this `dapis` (since there is no `passiveDapis`)

2023-10-25 12:17 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => UpdateParameters) private dapiNameHashToUpdateParameters;
Make this `dapiNameToUpdateParameters`. Also it shouldn't be private.

2023-10-25 12:17 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private activeDapis;
Also shouldn't be private

2023-10-25 12:17 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 public constant override DAPI_MANAGEMENT_HASH_TYPE =
btw these can be private

2023-10-25 12:18 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        IApi3ServerV1 _api3ServerV1
Validate that these are not zero

2023-10-25 12:19 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function hasRegistrarRoleOrIsManager(
You're only using this internally with `msg.sender`, so I don't see why this is not a modifier

2023-10-25 12:21 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function unregisterAirnodeSignedApiUrl(address airnode) external override {
Remove this

2023-10-25 12:24 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            );
A `dataFeedData.length` of 65 will not revert here. This is a much safer way of checking
```
(address[] memory airnodes, bytes32[] memory templateIds) = abi
                .decode(dataFeedData, (address[], bytes32[]));
require(abi.encode(airnode, templateIds).length == dataFeedData.length);
```

2023-10-25 12:26 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            );
This may also revert if `dataFeedData.length` is 0 so the validation above becomes redundant, gotta check

2023-10-25 12:27 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes memory newDataFeedData;
You shouldn't need this. Just revert if `dataFeedData` has trailing bytes and store `dataFeedData` otherwise.

2023-10-25 12:28 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            // TODO: check if signed API URL exists for Airnode?
No

2023-10-25 12:31 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
No need to validate these. You are validating `dapiName` in the function below though, so validate the others consistently.

2023-10-25 12:33 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        activeDapis.add(dapiName); // TODO: Not checking if already exists in set to allow for update parameters override (downgrade/upgrade)
Okay. Mention in `@dev` that the registrar is responsible with validating how the parameters are being overwritten

2023-10-25 12:34 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            deviationThresholdInPercentage, // TODO: can this be 0? should we check against any low/high boundary based on HUNDRED_PERCENT constant?
I think so? Gotta check what Airseeker does when it's configured as 0. Validating this is Api3Market's responsibility.

2023-10-25 12:34 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            heartbeatInterval // TODO: can this be 0?
Same as above

2023-10-25 12:35 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        emit UnregisteredDapi(dapiName); // TODO: add msg.sender?
Yes

2023-10-25 12:37 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        require(offset < count, "Invalid offset");
Return empty instead

2023-10-25 12:37 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            bytes32[] memory dataFeedIds,
This is redundant, can be derived from `dataFeedDatas`

2023-10-25 12:37 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            bytes[] memory dataFeedDatas,
Call this `dataFeeds`

2023-10-25 12:38 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    function readDapis(
This function should also call `api3ServerV1.dataFeeds(dataFeedId)` for each dAPI and return them

2023-10-25 12:42 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            uint256 currentIndex = i - offset;
`i` is short for index so having an `i` and a `currentIndex` in the same scope is confusing

2023-10-25 12:50 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +                signedApiUrls[currentIndex] = urls;
Something like this would be much smaller
```
signedApiUrls = abi.encodePacked(signedApiUrls, "\x1F", airnodeToSignedApiUrl[airnode]);
```

2023-10-25 13:09 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +                signedApiUrls[currentIndex] = urls;
btw I looked at the returned data and returning a signed API URL per Beacon doesn't look that bad

2023-10-25 13:10 UTC, bbenligiray requested changes
Let's merge this PR asap

2023-10-25 15:21 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private activeDapis;
I don't think Bytes32Set can be public. I get this when I try:

`Internal or recursive type is not allowed for public state variables.solidity(6744)`

2023-10-25 16:05 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    SelfMulticall,
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/22b984646929683b302d971cc7dcfb1f2a511f71

2023-10-25 16:05 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function registerDapi(
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/19c4d4121797be51c4b5a97764b47981c982cd1f

2023-10-25 16:06 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/5e3e7b4989294df47ce7dff1ba6991c26f0b23bd

2023-10-25 16:07 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            // TODO: check if signed API URL exists for Airnode?
https://github.com/api3dao/dapi-management/pull/3/commits/507922711d2360839b735f5de81de50d574920cd

2023-10-25 16:08 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    IApi3ServerV1 public immutable override api3ServerV1;
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/8f94c2eeb2318e0acbee1e5af30f393fba72655b

2023-10-25 16:09 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    // dAPI management merkle tree root
https://github.com/api3dao/dapi-management/pull/3/commits/26af162c80e73e85b83711f6d7d1397dc42d45d1

2023-10-25 16:09 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    // TODO: should this mapping be private now that we are returning these valuse via readDapis()
https://github.com/api3dao/dapi-management/pull/3/commits/5bd338872c73b728feaf046d8b2a537e41e6b7b0

2023-10-25 16:10 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => bytes) public override dataFeedIdToData;
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/5bd338872c73b728feaf046d8b2a537e41e6b7b0

2023-10-25 16:10 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private activeDapis;
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/1401563ad410cbdb2825d749c96a35d5e8022c42

2023-10-25 16:10 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    mapping(bytes32 => UpdateParameters) private dapiNameHashToUpdateParameters;
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/44cf3620f2b3cc3dabca1d2795d4ef73fc7d70cf

2023-10-25 16:11 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        IApi3ServerV1 _api3ServerV1
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/8f94c2eeb2318e0acbee1e5af30f393fba72655b

2023-10-25 16:11 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function unregisterAirnodeSignedApiUrl(address airnode) external override {
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/76d5e37381e1ea5883f4b8ec722721f8b92e2eff

2023-10-25 16:14 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            bytes[] memory dataFeedDatas,
Had to call it `dataFeeds_` to avoid naming collision with state var

2023-10-25 17:40 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function hasRegistrarRoleOrIsManager(
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/6d5f5c5d75dde09d8acee4f27dd52573679aacb1

2023-10-25 17:42 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
I thought this was a gas optimization thing and that is why it was also present [here](https://github.com/api3dao/manager-multisig/blob/main/chain/contracts/DapiFallbackV1.sol#L461-L466). I apply the suggested changes anyways

2023-10-25 18:05 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
@bbenligiray  actually, are you sure about this? If `airnode` is zero then the `root` will need to be something different from what was registered in the `HashRegistry`.  One thing I do wonder now that I'm looking at this is if we should check that the `root.timestamp` is not older than X days or something and not only check that the `root` was registered on the `HashRegistry`.

2023-10-25 18:49 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            );
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/5b3dd072be669df095fe6122d80de02740013d02

2023-10-25 18:57 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        bytes memory newDataFeedData;
I'm not too sure about this but I think it's fixed by https://github.com/api3dao/dapi-management/pull/3/commits/72c55bc1301ffb3f0f4e51bf8808dbefafa4e3c7

2023-10-25 18:59 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +                // TODO: check if signed API URL exists for Airnode?
https://github.com/api3dao/dapi-management/pull/3/commits/8ab2ed2355c5686f005765a8b2f1c36d5dcd971a

2023-10-25 18:59 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
Waiting for [this question](https://github.com/api3dao/dapi-management/pull/3#discussion_r1372137065) to be answered...

2023-10-25 19:08 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        emit UnregisteredDapi(dapiName); // TODO: add msg.sender?
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/03b7f4cc3f29ddbb35fe879fd079e84d59a46a36

2023-10-25 19:27 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(offset < count, "Invalid offset");
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/a9ad9ea6c6f9bf9b8ba357424ce2331bdbe6d585

2023-10-25 19:38 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            bytes32[] memory dataFeedIds,
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/04059fe3904bbefd842fcbca407b8bfcfa494824

2023-10-25 19:43 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            uint256 currentIndex = i - offset;
Maybe then: `ind`, `currentInd` and `ind2` https://github.com/api3dao/dapi-management/pull/3/commits/c1e63f96a94443e83de804662316a24249065bcc

2023-10-25 20:42 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    function readDapis(
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/b01c277708e7a56c31cbccd44637865fc589218c

2023-10-26 12:13 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            deviationThresholdInPercentage, // TODO: can this be 0? should we check against any low/high boundary based on HUNDRED_PERCENT constant?
Currently it seems that deviation = 0 is equal to "update always" in Airseeker:
1. not validating value from config: https://github.com/api3dao/airseeker/blob/main/src/validation.ts#L137
2. not checking in condition function: https://github.com/api3dao/airseeker/blob/main/src/check-condition.ts#L44

2023-10-26 12:52 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +                signedApiUrls[currentIndex] = urls;
and how do you feel about packing each Airnode Signed API URL along with each data feed data encoded object? This doesn't dedup the urls and requires the use of standard `abi.encode` but it makes the payload simpler to use:

```
    function readDapis(
        uint256 offset,
        uint256 limit
    )
        external
        view
        override
        returns (
            bytes32[] memory dapiNames,
            UpdateParameters[] memory updateParameters,
            DataFeedValues[] memory dataFeedValues,
            bytes[] memory dataFeedsWithSignedApiUrls
        )
    {
        uint256 count = dapisCount();
        if (offset < count) {
            uint256 limitAdjusted = offset + limit > count
                ? count - offset
                : limit;
            dapiNames = new bytes32[](limitAdjusted);
            updateParameters = new UpdateParameters[](limitAdjusted);
            dataFeedValues = new DataFeedValues[](limitAdjusted);
            dataFeedsWithSignedApiUrls = new bytes[](limitAdjusted);
            for (uint256 ind = offset; ind < offset + limitAdjusted; ind++) {
                bytes32 dapiName = _dapis.at(ind);
                uint256 currentInd = ind - offset;
                dapiNames[currentInd] = dapiName;
                bytes32 dapiNameHash = keccak256(abi.encodePacked(dapiName));
                bytes32 dataFeedId = IApi3ServerV1(api3ServerV1)
                    .dapiNameHashToDataFeedId(dapiNameHash);
                (int224 value, uint32 timestamp) = IApi3ServerV1(api3ServerV1)
                    .dataFeeds(dataFeedId);
                dataFeedValues[currentInd] = DataFeedValues(value, timestamp);
                updateParameters[currentInd] = dapiNameToUpdateParameters[
                    dapiNameHash
                ];
                bytes memory dataFeed = dataFeeds[dataFeedId];
                if (dataFeed.length == 64) {
                    (address airnode, bytes32 templateId) = abi.decode(
                        dataFeed,
                        (address, bytes32)
                    );
                    dataFeedsWithSignedApiUrls[currentInd] = abi.encode(
                        airnode,
                        templateId,
                        airnodeToSignedApiUrl[airnode]
                    );
                } else {
                    (
                        address[] memory airnodes,
                        bytes32[] memory templateIds
                    ) = abi.decode(dataFeed, (address[], bytes32[]));
                    string[] memory urls = new string[](airnodes.length);
                    for (uint256 ind2 = 0; ind2 < airnodes.length; ind2++) {
                        urls[ind2] = airnodeToSignedApiUrl[airnodes[ind2]];
                    }
                    dataFeedsWithSignedApiUrls[currentInd] = abi.encode(
                        airnodes,
                        templateIds,
                        urls
                    );
                }
            }
        }
    }
```

2023-10-26 18:52 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        activeDapis.add(dapiName); // TODO: Not checking if already exists in set to allow for update parameters override (downgrade/upgrade)
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/49eae4e5929a4211546c12cc056bacfaff54fc6f

2023-10-26 18:56 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
I know even think that the check on `dapiName` is redundant on `removeDapi()` below so I removed it https://github.com/api3dao/dapi-management/pull/3/commits/4e8e5c5cddbec5a8d41d4452f22d68e2fcf17a63

2023-10-26 18:58 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private activeDapis;
In `HashRegistry` I workaround it by doing [this](https://github.com/api3dao/dapi-management/blob/169-DapiDataRegistry/contracts/HashRegistry.sol#L107C9-L107C9)

2023-10-27 08:34 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +                signedApiUrls[currentIndex] = urls;
I'm on the edge but leaning towards not liking it because a signed API URL belongs to an Airnode and not a data feed, associating it with the data feed comes off as wrong to me (though the alternative also does that implicitly).

> it makes the payload simpler to use

I'm not seeing that tbh. You already need to match dAPI names to data feeds, also requiring to match the signed API URLs to data feeds doesn't feel too much at that point. What would actually be easy to use for this to return a `Dapi` struct that includes both the name, data feeds, their URLs, etc.

2023-10-27 13:19 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
> If airnode is zero then the root will need to be something different from what was registered in the HashRegistry

Not if the Merkle tree whose root is registered at `HashRegistry` includes a zero `airnode` address

2023-10-27 13:20 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
```suggestion
    bytes32 private constant DAPI_MANAGEMENT_MERKLE_TREE_ROOT_HASH_TYPE =
```

2023-10-27 13:20 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        keccak256(abi.encodePacked("Signed API URL Merkle root"));
```suggestion
    bytes32 private constant SIGNED_API_URL_MERKLE_TREE_ROOT_HASH_TYPE =
        keccak256(abi.encodePacked("Signed API URL Merkle tree root"));
```

2023-10-27 13:21 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private _dapis;
```suggestion
    EnumerableSet.Bytes32Set private dapis;
```

2023-10-27 13:22 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +            "Sender is not manager or needs Registrar role"
```suggestion
            "Sender is not manager or has Registrar role"
```

2023-10-27 13:24 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
Imo Merkle tree values need to be validated wherever possible https://github.com/api3dao/dapi-management/pull/17#discussion_r1374555280

2023-10-27 13:26 UTC, bbenligiray commented on contracts/DapiDataRegistry.sol
> +        bytes calldata dataFeed
Check if `else` reverts when `dataFeed.length == 0` and revert explicitly if not

2023-10-27 14:24 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +                signedApiUrls[currentIndex] = urls;
I guess this becomes obsolete now that [readDapis()](https://github.com/api3dao/dapi-management/pull/3/commits/4aceef94c1911eaccd7b71bf2d786c313830224f) no longer exists and dAPIs must be fetched one by one (via multicall) based on [this](https://api3workspace.slack.com/archives/C027Y2FAV0S/p1698326968765089) and [this](https://api3workspace.slack.com/archives/C027Y2FAV0S/p1698327049106809) comments.

I don't have a strong opinion on using or not a `Dapi` struct but one thing that is now a concern for me is: how difficult would be it be for callers to decode the existing structs (`UpdateParameters` and `DataFeedValue`) with something like ethers.js when calling this functions via static `multicall()` which returns [encoded](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/utils/SelfMulticall.sol#L21) results.

2023-10-27 14:29 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    bytes32 private constant _DAPI_MANAGEMENT_HASH_TYPE =
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/2682e771c539eebf2e13cc21d893b3d0f689d840

2023-10-27 14:30 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        keccak256(abi.encodePacked("Signed API URL Merkle root"));
Good catch. Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/2682e771c539eebf2e13cc21d893b3d0f689d840

2023-10-27 14:33 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +    EnumerableSet.Bytes32Set private _dapis;
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/a088d2459cf1674f69c6de5b4fc29a2cb8ff01ba

2023-10-27 14:33 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            "Sender is not manager or needs Registrar role"
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/e7339c885fe1cfe90ccaf2eb51105875b7379262

2023-10-27 14:58 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/05d1ed6880dfe2bfc14159f4b1b613ff3e34029a

2023-10-27 14:59 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        require(proof.length != 0, "Proof is empty");
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/b0f812b515ef0563f4bf8ad7fff2df83535d66cc

2023-10-27 15:04 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        bytes calldata dataFeed
I have a[ test for this case](https://github.com/api3dao/dapi-management/blob/169-DapiDataRegistry/test/DapiDataRegistry.sol.js#L437) and it does revert without reason so I'll add a `require()`

2023-10-27 15:08 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +        bytes calldata dataFeed
Fixed in https://github.com/api3dao/dapi-management/pull/3/commits/00b25a6b52d93382664fa04fc955fe53ba12065d

2023-10-31 15:04 UTC, merged