Function to be able to switch back from fallback on a specific dAPI
api3dao/dapi-management pull request #32
Opened 2023-10-31 21:33 UTC by acenolaza

While thinking about merging (inherit) `DapiFallbackV2` with `Api3Market` I remembered that `DapiFallbackV2` must be kept funded in order to be able to send funds to the self funded sponsor wallet in the case of calling `executeDapiFallback()`. It seems to me that it might not be a good idea to keep and transfer funds from the same contract that receives payments for managed dAPIs. Therefore keeping the separation of concerns seems to still be a good idea after all and I even applied the same logic for the new list of dAPIs for which `executeDapiFallback()` has been called. Having this list in `DapiDataRegistry` did not look appropriate and everything fallback related should be in the `DapiFallbackV2`. 

With that said, I see two main drawbacks:
1. `DapiFallbackV2` will require the `addDapi` and `removeDapi` roles to be granted
2. Market UI will need to use a separate RPC call to fetch the list of fallbacked dAPIs

I've created this branch out of main branch because I ended up not touching the Api3Market contract. Please share your thoughts  🙏🏻  (as usual I left TODOs with questions/concerns)

2023-10-31 21:41 UTC, acenolaza commented on contracts/DapiDataRegistry.sol
> +            DAPI_REMOVER_ROLE_DESCRIPTION
I felt lazy for not using a separate role and now I had an excuse for doing so 😄

2023-10-31 21:42 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +    function revertDapiFallback(
natspec comments are missing but will be added once and if we decide this is a valid approach

2023-11-01 05:36 UTC, alikonuk1 requested changes

2023-11-01 05:36 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +        //       Should we store the dataFeedId and sponsorWallet used on executeDapiFallback? update params
Would it be better if UI fetch those values from Nodary for fallbacked dapis?

2023-11-01 05:57 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
I think the thought process was to keep fallback flow to be less dependent on just owners but giving more flexibility to anyone who has the right values to execute. But I see your point, some malicious actor can constantly execute fallbacks.

2023-11-01 13:42 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +        IDapiDataRegistry(dapiDataRegistry).removeDapi(args.dapiName);
Fixed in https://github.com/api3dao/dapi-management/pull/32/commits/2f253ab2ed5633472efaab527d7f79768baa8fa5

2023-11-01 13:46 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +        );
I did add the `require` check on [`remove()`](https://github.com/api3dao/dapi-management/blob/DapiFallbackV2-DapiDataRegistry/contracts/DapiDataRegistry.sol#L268) but I'm not so sure we need it in [`add()`](https://github.com/api3dao/dapi-management/blob/DapiFallbackV2-DapiDataRegistry/contracts/DapiDataRegistry.sol#L235) because this is the intended way of updating the update parameters for an already added dAPI ([upgrade/downgrade](https://github.com/api3dao/dapi-management/blob/DapiFallbackV2-DapiDataRegistry/contracts/DapiDataRegistry.sol#L182-L185))

2023-11-01 14:07 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +        //       Should we store the dataFeedId and sponsorWallet used on executeDapiFallback? update params
Right, I was thinking the same thing 👍🏻 
Fixed in https://github.com/api3dao/dapi-management/pull/32/commits/89ba7d0c3bb0367422abb9912160c613e1875355

2023-11-01 15:26 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
Right, and also since DapiDataRegistry.addDapi() and DapiDataRegistry.removeDapi() are behind access control then it seems wrong to me that DapiFallbackV2.executeDapiFallback() and DapiFallbackV2.revertDapiFallback() are not behind some access control check too.

2023-11-01 16:27 UTC, acenolaza commented
@alikonuk1 Since there seems to be no major objections to this approach over the merging of this contract with Api3Market contract then I'm setting this as "Ready for review"

2023-11-01 16:35 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +        );
My bad, its more clear now.

2023-11-01 16:40 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
Should we do this on this PR or add it later?

2023-11-01 19:27 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
TBH I'm not sure. Maybe it's OK that anyone can switch to fallback but I'm really uncomfortable letting anyone switch a dAPI to any data feed in the merkle tree 🤷🏻 WDYT?

2023-11-01 20:35 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
How does this sound, lets put some access control and give access to larger group of people than signers. This way, we won't need just signers to execute but will also have other "less-trusted" executors who can step up and execute a fallback in times of emergency.

2023-11-01 21:44 UTC, acenolaza commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
Right, similar to the `dapiFallbackExecutors` list we used to have. I guess it only makes sense that dAPI management merkle tree root signers are allow to execute / revert dAPIs fallback. I'm thinking thinking that fallback merkle tree root signers should be left out from the executors list (this used to be the way in V1)

2023-11-06 09:48 UTC, alikonuk1 commented on contracts/DapiFallbackV2.sol
> +    // previous payed dAPI subscription. Why anyone can call executeDapiFallback?
Added necessary checks in [d472736](https://github.com/api3dao/dapi-management/pull/32/commits/d472736082ef684e4a6a96913bf83c87d445ddf4)

2023-11-06 09:56 UTC, alikonuk1 approved these changes
LGTM

2023-11-06 17:27 UTC, merged