Script for updating dapi fallback hash merkle tree values
api3dao/dapi-management pull request #34
Opened 2023-11-03 14:02 UTC by pieterdub

Closes #23

- [ x ]  Add script to check if there are new values on `@nodary/utilities` package
- [ x ]  Update Readme to include instructions to use script

2023-11-06 13:44 UTC, mcoetzee requested changes

2023-11-06 13:44 UTC, mcoetzee commented on scripts/syncTreeValues.js
> +    console.info('Current hash file is up to date!');
Very minor: Don't think we need to add exclamation marks 🙂

2023-11-06 13:44 UTC, mcoetzee commented on scripts/syncTreeValues.js
> +function getExistingTreeValues(merkleTreeName) {
Following prev feedback, there is no need for this function, we can just call `getNodaryFallbackValues()`

2023-11-06 13:44 UTC, mcoetzee commented on scripts/syncTreeValues.js
> +//#region DAPI Fallback values fetch
Minor: These `#region ` and `#endregion` comments seems a bit unusual?

2023-11-06 13:44 UTC, mcoetzee commented on package.json
> +    "sync-tree-values": "node scripts/syncTreeValues.js",
Following prev feedback, we can name this less broadly. Perhaps:
```json
"sync-dapi-fallback-values": "node scripts/sync-dapi-fallback-values.js",
```
Also, lets stick to `kebab-case` when naming files.

2023-11-06 13:44 UTC, mcoetzee commented on scripts/README.md
> +## Usage Of Update DApi Fallback hash
This heading isn't too clear to me. What about calling the section: _How to update the dAPI Fallback Merkle Tree_

Step one would be to update the `@nodary/utilities` package.

Also, following prev feedback, remember to update the below

2023-11-06 13:44 UTC, mcoetzee commented on scripts/README.md
> +It saves the `current-hash.json` to `previous-hash.json` and updates `current-hash.json` with the new values.
Minor: `It` shouldn't be capitalised

2023-11-06 18:40 UTC, pieterdub commented on scripts/syncTreeValues.js
> +  if (isEqual(currentHashValues, values)) {
Cool cool thanks 🙏

2023-11-06 18:40 UTC, pieterdub commented on scripts/syncTreeValues.js
> +const MERKLE_TREE_MAPPING = {
Good to know 👍

2023-11-07 07:17 UTC, mcoetzee approved these changes
Just got one last comment, so I'm approving so long 👍

2023-11-07 07:17 UTC, mcoetzee commented on data/dapi-fallback-merkle-tree-root/current-hash.json
> +  "signatures": {},
We need to keep the current `signatures` and `timestamp`.

2023-11-07 08:42 UTC, merged