Implement Sign Root button
api3dao/dapi-management pull request #42
Opened 2023-11-13 08:54 UTC by pieterdub

Closes #22 

Add utility function to construct the combined hash for a tree given the `hashType`, `treeRoot` and `timestamp`. Use this has to sign the message using metamask and send it with the address and treeType to the backend endpoint to update the `current-hash.json`.

- [ ] Add utility function to create the combined hash
- [ ] Update dapi fallback tree by implementing the Sign Root button
- [ ] Add `Toast` from `chan-cn` for feedback when interacting with the Sign Root button
- [ ] Use the same method in the `signMerkleTree` script to generate the combined hash and sign.

2023-11-13 11:39 UTC, alikonuk1 requested changes

2023-11-13 11:39 UTC, alikonuk1 commented on scripts/signMerkleTree.js
> +  const encodedHash = ethers.utils.toUtf8Bytes('dAPI fallback Merkle tree root');
Shouldnt this get an input of the tree type rather than hardcoding `'dAPI fallback Merkle tree root'`?

2023-11-13 12:05 UTC, pieterdub commented on scripts/signMerkleTree.js
> +  const encodedHash = ethers.utils.toUtf8Bytes('dAPI fallback Merkle tree root');
Yes indeed 👍

2023-11-13 14:01 UTC, mcoetzee requested changes
Nice one for figuring out how to derive the tree hash 👍

2023-11-13 15:01 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
Just added this as a visual queue to the Sign Root button to make it disabled

2023-11-14 07:22 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
Hmm not sure I follow? I'm only referring to the `connectStatus === 'connected'` check.

2023-11-14 08:03 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
I see what you mean but `signatures[address] === '0x'` will never be true if the signer is not in signatures, it will rather be undefined. I am going to change it to  
```  
const canSign = isSigner && signatures[address] === '0x' && !isSigning;
```

2023-11-14 08:10 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
> I see what you mean but signatures[address] === '0x' will never be true if the signer is not in signatures

Yes that is why it works. `signatures[address] === '0x'` will only be true if you are a signer and your signature is pending.

2023-11-14 08:14 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
But in the `sync-dapi-fallback-values` script we set the signatures to 
```
    const merkleTeeData = {
      timestamp: new Date().getTime(),
      hash: tree.root,
      signatures: {},
      merkleTreeValues: { values },
    };
```
So the button will never become enabled currently 🤔

2023-11-14 08:17 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
These ^^ are the validated signatures:
```ts
const signatures = validateTreeRootSignatures(...);
```

2023-11-14 08:20 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-fallback.tsx
> +  const canSign = (signatures[address] === '0x' || !isLoading) && connectStatus === 'connected';
lol I noticed that after I made my comment 😄

2023-11-14 08:37 UTC, mcoetzee approved these changes
Nice one 👍

2023-11-14 08:43 UTC, merged