Add dAPI pricing merkle tree page
api3dao/dapi-management pull request #49
Opened 2023-11-16 12:40 UTC by pieterdub

Closes #36 

Using previous trees as reference create `dapi-pricing-merkle-tree` page.

Cleanup `dapi-management` by using common `SignButton` component

<img width="1788" alt="image" src="https://github.com/api3dao/dapi-management/assets/46445845/899c5c92-8799-4daf-87b7-44167817bf5e">

2023-11-17 08:41 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{pricing[4]}</TableCell>
Should we format these prices like `1,000.00`?

2023-11-17 09:34 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{pricing[4]}</TableCell>
mmm... I am not sure what numbers to expect here. I tried adding test data like `232.45` but that bombs out when constructing the merkle tree giving error `invalid BigNumber string` I will do some investigation into this though. Would be nice to format it

2023-11-17 15:12 UTC, bbenligiray commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{pricing[4]}</TableCell>
The tree values will be in Wei. It would be ideal if these were displayed in value + unit where the unit is a dropdown that autoselects `ether`

2023-11-20 13:54 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{pricing[4]}</TableCell>
I have added the unit selection as requested, it defaults to `ether`

<img width="489" alt="image" src="https://github.com/api3dao/dapi-management/assets/46445845/b084dc90-5d91-45a7-b736-1d300556cafd">

<img width="437" alt="image" src="https://github.com/api3dao/dapi-management/assets/46445845/57180866-4df9-4209-9e6d-37f0c9896399">

2023-11-20 15:14 UTC, mcoetzee requested changes

2023-11-20 15:14 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{convertWeiTo(priceUnit, pricing[4])}</TableCell>
Ethers has got utilities for formatting:
```tsx
priceUnit === 'ether' 
  ? ethers.utils.commify(ethers.utils.formatEther(price)) 
  : price
```

2023-11-20 15:14 UTC, mcoetzee commented on frontend/lib/utils.ts
> +export function convertWeiTo(unit: Unit, weiInput: string) {
Following prev comment, this can be removed.

2023-11-20 15:14 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                <TableHead className="flex items-center gap-2">
A table cell by default displays as `display: table-cell`, changing it to anything else has side effects. Lets rather remove these classes from the `<th>`, we can achieve the same by giving the select trigger an inline display.

2023-11-20 15:14 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                    <SelectTrigger className="w-[100px]">
Should we reduce the height of the trigger a bit? 
```tsx
<SelectTrigger className="ml-1 inline-flex h-8 w-[100px]">
```

2023-11-20 15:14 UTC, mcoetzee commented on data/dapi-pricing-merkle-tree-root/current-hash.json
> +      ["AAPL/USD", "1", "0x2345678901234567890123456789012345678901234567890123456789012345", "3600", "1000"],
I know this is mock data, but can you use Wei units for the prices here so that it doesn't format to a super tiny price.

2023-11-21 05:59 UTC, pieterdub commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +                  <TableCell>{convertWeiTo(priceUnit, pricing[4])}</TableCell>
Good to know 👍

2023-11-21 07:14 UTC, mcoetzee approved these changes
Just one last minor comment, so I'm approving so long 👍

2023-11-21 07:14 UTC, mcoetzee commented on frontend/pages/merkle-trees/dapi-pricing.tsx
> +export type Unit = 'wei' | 'ether';
Minor: We don't need to export this.

2023-11-21 08:31 UTC, merged