Add github action to update data folder contents
api3dao/dapi-management pull request #61
Opened 2023-11-23 11:02 UTC by pieterdub

Closes #6 

`github-pages.yml` has been created to include new changes to the `data` folder into `gh-pages` branch. Which has been set up to deploy `gh-pages` to the github pages api. 

Steps include:

1.  Checkout main
2. Switch branch to `gh-pages`
3. checkout data folder on main into `gh-pages`
4. Commit and push if there are any changes

To access github pages one can navigate to:

`https://api3dao.github.io/dapi-management/data/<merkle-tree-path>/current-hash.json`

For example 
`https://api3dao.github.io/dapi-management/data/dapi-fallback-merkle-tree-root/current-hash.json`

2023-11-24 08:12 UTC, mcoetzee requested changes
Nice one 👍

I just had a look at the `gh-pages` branch, and can we re-create it, so that we can get rid of all your test commits.

2023-11-24 08:12 UTC, mcoetzee commented on .github/workflows/README.md
> +This GitHub Actions workflow automates the process of deploying new files from the main branch to the gh-pages branch, updating the contents of a `data` folder.
Hmm this doesn't sound quite right to me. 
```
automates the process of deploying new files
```
How I understand it, is that the GH workflow detects changes to the `data` folder on the `main` branch, and pushes those changes to the `gh-pages` branch. That's it. GH pages then takes care of deploying the `gh-pages` branch.

2023-11-24 14:53 UTC, pieterdub commented on .github/workflows/github-pages.yml
> +          git push --set-upstream origin gh-pages
Yes you are correct

2023-11-27 07:53 UTC, mcoetzee approved these changes
Nice one 👍

2023-11-27 08:24 UTC, merged