Extend the CI to verify the Data Feed IDs and Sponsor Wallet Addresses
api3dao/dapi-management pull request #91
Opened 2023-12-06 14:45 UTC by mcoetzee

2023-12-07 10:40 UTC, mcoetzee commented
FYI @metobom 
> - extracts the logic to derive data feed IDs and sponsor wallet addresses from `generate-dapi-management-mt.js` to `scripts/utils.js` and uses these function in both `generate-dapi-management-mt.js` and `verify-dapi-management-data.js`

Feel free to leave comments on these changes.

2023-12-07 10:45 UTC, metobom commented
> Feel free to leave comments on these changes.

Makes sense since they will be used in multiple places.

2023-12-11 07:43 UTC, pieterdub requested changes
Few minor comments, happy to discuss if they are to petty 😄

2023-12-11 07:43 UTC, pieterdub commented on scripts/verification/verify-dapi-management-data.js
> +  console.info('Verifying dAPI Management data locally...');
It is not really helpful to see `locally` in the CI. Could add confusion.
```suggestion
  console.info('Verifying dAPI Management data...');
```

2023-12-11 07:43 UTC, pieterdub commented on scripts/verification/verify-dapi-pricing-data.js
> +  console.info('Verifying dAPI Pricing data locally...');
Same here

2023-12-11 07:43 UTC, pieterdub commented on scripts/verification/verify-signed-api-url-data.js
> +  console.info('Verifying Signed API URL data locally...');
Ditto

2023-12-11 07:43 UTC, pieterdub commented on scripts/generate-dapi-management-mt.js
> +const dapis = require('../data/dapis.json');
Do we want to include `../data/dapis.json` in the .gitignore file 🤔 

Will there be similar `dapis.json` files for the other trees? If so perhaps it should be moved to the `dapi-management` data folder

2023-12-11 07:43 UTC, pieterdub commented on scripts/verification/verify-dapi-management-data.js
> +  currentHashData.merkleTreeValues.forEach((values) => {
```suggestion
  currentHashData.merkleTreeValues.forEach((value) => {
```

2023-12-11 07:43 UTC, pieterdub commented on scripts/verification/verify-signed-api-url-data.js
> +  currentHashData.merkleTreeValues.forEach((values) => {
```suggestion
  currentHashData.merkleTreeValues.forEach((value) => {
```

2023-12-11 08:06 UTC, mcoetzee commented on scripts/generate-dapi-management-mt.js
> +const dapis = require('../data/dapis.json');
> Do we want to include ../data/dapis.json in the .gitignore file

The file was added as part of this [PR](https://github.com/api3dao/dapi-management/pull/79) (script that generates dAPI management mt data), and we definitely don't want to delete it 🙂

2023-12-11 08:26 UTC, mcoetzee commented on scripts/verification/verify-dapi-management-data.js
> +  currentHashData.merkleTreeValues.forEach((values) => {
We are dealing with an array of arrays, so imo it's not ideal to give an array a singular variable name.

2023-12-11 08:43 UTC, pieterdub commented on scripts/verification/verify-dapi-management-data.js
> +  console.info('Verifying dAPI Management data locally...');
I understand, perhaps `Verifying dAPI Management local data...` but happy if you keep it as is 👍 

Thanks for the explanation

2023-12-11 08:46 UTC, pieterdub commented on scripts/verification/verify-dapi-management-data.js
> +  currentHashData.merkleTreeValues.forEach((values) => {
True, the only reason I like the singular form is that this particular array pertains to a single tree value. But I suppose each tree entry has multiple values so happy if you keep it as is

2023-12-11 08:57 UTC, pieterdub approved these changes
LGTM thanks for a few explanations

2023-12-11 09:12 UTC, merged